export default {
	ADD_NEW_MOUNTAIN: 'ADD_NEW_MOUNTAIN',
  ADD_MOUNTAINS_FROM_SERVER: 'ADD_MOUNTAINS_FROM_SERVER',
  CHECK_MOUNTAIN: 'CHECK_MOUNTAIN',
  UNCHECK_MOUNTAIN: 'UNCHECK_MOUNTAIN',

  FACEBOOK_LOGIN_CHANGE: 'FACEBOOK_LOGIN_CHANGE',
  FACEBOOK_GETTING_PICTURE: 'FACEBOOK_GETTING_PICTURE',
  FACEBOOK_RECEIVED_PICTURE: 'FACEBOOK_RECEIVED_PICTURE',
  FACEBOOK_LOGGED_IN: 'FACEBOOK_LOGGED_IN',
  FACEBOOK_LOGGED_OUT: 'FACEBOOK_LOGGED_OUT',

  NEW_USER: 'NEW_USER',
  REQUEST_USER_FROM_SERVER: 'REQUEST_USER_FROM_SERVER'
}
